### ISSUE TITLE
Failed to resolve: ua.com.crosp.solutions.library:presenter-layout:0.1.0

### ISSUE THREAD

**Issue by jp1017** [CROSP/presenter-layout#1]
Error:(24, 13) Failed to resolve: ua.com.crosp.solutions.library:presenter-layout:0.1.0

Can you？

**Comment by CROSP** [comment]
@jp1017  thank you for posting this issue. I have forgotten to change repo description.
Please use `compile 'ua.com.crosp.solutions.library:presenter-layout:0.1.1'` instead.
Thanks

**Comment by jp1017** [comment]
Wonderful, 3ks, boy. :smiley:
